OTAutoSearch/OTAutoSearch/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'OTAutoSearch.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^ot/',include('OTobjects.urls',namespace="OTobjects")),
    #url(r'^accounts/', include('registration_email.backends.default.urls')),
)

OTAutoSearch/OTobjects/urls.py
from django.conf.urls import *
from OTobjects import views

#phref_dic = {'phref':'/ot/index/'}

urlpatterns = patterns('',
   url(r'index$',views.Index,name='index'),
   url(r'confirm_login-form$',views.LoginForm,{'confirm':True},name='conlogin_form'),
   url(r'login-form$',views.LoginForm,name='login_form'),
   url(r'confirm_login',views.Login,{'confirm':True},name='confirm_login'),
   url(r'login$',views.Login,name='login'),
   url(r'logout$',views.Logout,name='logout'),
   url(r'signup-form$',views.SignupForm,name='signup_form'),
   url(r'signup$',views.Signup,name='signup'),
   url(r'status=(?P<status>-?\d{1})/$',views.Index,name='index_status'),
   url(r'status=(?P<status>-?\d)/page=(?P<page>\d+)$',views.Index,name='index_status_page'),
   url(r'page=(?P<page>\d+)$',views.Index,name='index_page'),
   url(r'image/otid=(?P<otid>\d+)/$',views.ShowImage,name='image'),
   url(r'image/otid=(?P<otid>\d+)/?index=lc/$',views.ShowLightCurve, name='lc'),
   url(r'image/otid=(?P<otid>\d+)/?index=fchart/$',views.ShowFchart,name='fchart'),
   url(r'image/otid=(?P<otid>\d+)/?index=confirm/$',views.Confirm,name='confirm'),
   url(r'image/otid=(?P<otid>\d+)/?index=status/$',views.ChangeStatus,name='changestatus'),
   url(r'image/otid=(?P<otid>\d+)/?index=comment/$',views.Comment,name='comment'),
)

OTAutoSearch/OTobjects/models.py
from django.db import models
import os
from OTAutoSearch.settings import base_path,static_path

Fchart_path = os.path.join(static_path,'OTobjects/Fchart')
# Create your models here.
class OTuniq(models.Model):
    STATUS_CHOICES = ((-1,'False transient'),(0,'To be confirmed'),(1,'True transient'),(2,'Continue to be confirmed'),)
    OTid = models.AutoField(primary_key=True,db_index=True)
    x = models.FloatField()
    y = models.FloatField()
    Ra = models.FloatField()
    Dec = models.FloatField()
    skyid = models.CharField(max_length=6,db_index=True)
    magcalib = models.FloatField()
    magres = models.FloatField()
    magErr = models.FloatField()
    magorig = models.FloatField()
    magorigErr = models.FloatField()
    magref = models.FloatField()
    magrefErr = models.FloatField()
    counts = models.IntegerField(default=1)
    c_filter = models.FloatField()
    status = models.IntegerField(max_length=1,choices=STATUS_CHOICES,default=0)

    class Meta:
        db_table = 'otuniq'
        ordering = ['OTid']
    def __unicode__(self):
        return str(self.OTid)

class Catfiles(models.Model):
    Catid = models.AutoField(primary_key=True,db_index=True)
    Catna = models.CharField(max_length=50,unique=True)
    orig_im = models.CharField(max_length=50)
    ref_im = models.CharField(max_length=50)
    JD = models.FloatField()
    mountid = models.CharField(max_length=2)
    cameraid = models.CharField(max_length=2)
    ymd = models.CharField(max_length=6)
    skyid = models.CharField(max_length=6)
    mcysids = models.CharField(max_length=19)

    class Meta:
        db_table = 'catfiles'
        ordering = ['Catid']
    def __unicode__(self):
        return str(self.Catid)

class OTcands(models.Model):
    OTid = models.ForeignKey(OTuniq,db_column='OTid')
    Catid = models.ForeignKey(Catfiles,db_column='Catid')
    x = models.FloatField()
    y = models.FloatField()
    Ra = models.FloatField()
    Dec = models.FloatField()
    magres = models.FloatField()
    magresErr = models.FloatField()
    magorig = models.FloatField()
    magorigErr = models.FloatField()
    magrescalib = models.FloatField()
    filter = models.IntegerField(max_length=1)
    tag_refstr = models.IntegerField(max_length=1)

    class Meta:
        db_table = 'otcands'
        ordering = ['OTid','Catid']
    def __unicode__(self):
        return str(self.OTid)

class Fchart(models.Model):
    OTid = models.ForeignKey(OTuniq,db_column='OTid')
    Catid = models.ForeignKey(Catfiles,db_column='Catid')
    Fname = models.CharField(max_length=50,unique=True)
    Fpath = models.CharField(max_length=100,default=Fchart_path)

    class Meta:
        db_table = 'fchart'
        ordering = ['OTid','Catid']
    def __unicode__(self):
        return str(self.OTid)

class Users(models.Model):
    uid = models.AutoField(primary_key=True,db_index=True)
    uname = models.CharField(max_length=16,unique=True,db_index=True)
    passwd = models.CharField(max_length=50)
    email_add = models.EmailField()
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=30)
    status = models.NullBooleanField(default=False)
    
    class Meta:
        db_table = 'users'
        ordering = ['uid']
    def __unicode__(self):
        return str(self.uid)

class Comments(models.Model):
    STATUS_CHOICES = ((-1,'False transient'),(0,'To be confirmed'),(1,'True transient'),(2,'Continue to be confirmed'),)
    OTid = models.ForeignKey(OTuniq,db_column='OTid')
    uid = models.ForeignKey(Users,db_column='uid')
    status = status = models.IntegerField(max_length=1,choices=STATUS_CHOICES,default=0)
    comment = models.TextField(blank=True)
    datetime = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        db_table = 'comments'
        ordering = ['OTid']
    def  __unicode__(self):
        return str(self.OTid)

OTAutoSearch/OTobjects/views.py
from django.shortcuts import render,render_to_response
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator
from OTobjects.models import OTuniq as Model1, OTcands as Model2, Catfiles as Model3, Fchart as Model4, Comments as Model5, Users as Model6
import scipy as sp

global OTid 

# Create your views here.
def Index(request,status=None,page=None,per_page=30):
    '''page     : the current page
       per_page : the number of records in pre page
    '''
    #-page
    if page == None:
        page = 1
    else:
        page = int(page)
    if page >= 4:
        page_start = page-2
        page_end = page+7
    else:
        page_start = 1
        page_end = 1
    #- check the user from the session
    if 'user_id' in request.session:
        user = Model6.objects.get(uid=request.session['user_id'])
        username = user.uname
        userstatus = True
    else:
        username = None
        userstatus = False
    #-Select from OTuniq
    if status:
        otm1 = Model1.objects.filter(status=status).order_by('-counts')
    else:
        otm1 = Model1.objects.order_by('-counts')
    #-Paginator
    paginator = Paginator(otm1,per_page)
    otm1 = paginator.page(page)
    dic = {'otm1':otm1,'paginator':paginator,'page':page,'page_start':page_start,'page_end':page_end,'username':username,'userstatus':userstatus}
    return render(request,'OTobjects/index.html',dic)

def ShowImage(request,otid):
    global OTid
    OTid = str(otid)
    return render_to_response('OTobjects/showImage.html')


def ShowLightCurve(request,otid,JDC=2450000):
    #-Select from OTcands
    otm2 = Model2.objects.filter(OTid=otid)
    jdmag = sp.asarray([[ot.Catid.JD,ot.magorig]for ot in otm2])
    jdmag[:,0] = jdmag[:,0]-JDC
    jdmag = jdmag[jdmag[:,0].argsort()]
    #jdmag = sp.loadtxt('/home/madong/projects/django/OTAutoSearch/OTobjects/OGLE-SMC-LPV-00189.dat',usecols=[0,1])
    jdmag = jdmag.tolist()    
    dic = {'jdmag':jdmag,'jdc':JDC,'otid':otid}
    return render(request,'OTobjects/showLightCurve.html',dic)

def ShowFchart(request,otid):
    #-Select from Fchart
    otm4 = Model4.objects.filter(OTid=otid)
    dic = {'otm4':otm4,'otid':otid}
    return render(request,'OTobjects/showFchart.html',dic)

def Confirm(request,otid):
    #-Check whether the user login
    if 'user_id' in request.session:
        #-Select from Fchart
        otm4_0 = Model4.objects.filter(OTid=otid).first()
        #-Select from Comments
        otm5 = Model5.objects.filter(OTid=otid)
        counts = otm5.count()
        dic = {'otm4_0':otm4_0,'counts':counts,'otm5':otm5}
        return render(request,'OTobjects/confirm.html',dic)
    else:
        return HttpResponseRedirect('/ot/confirm_login-form')

def ChangeStatus(request,otid):
    #-Update OTuniq and Comments
    if request.POST:
        Model1.objects.filter(OTid=otid).update(status=request.POST['status'])
        otm5UidOtidIsExist = Model5.objects.filter(OTid=otid,uid=request.session['user_id'])
        if otm5UidOtidIsExist:
            otm5UidOtidIsExist.update(status=request.POST['status'])
        else:
            Model5.objects.create(OTid_id=otid,uid_id=request.session['user_id'],status=request.POST['status'])
    #-Select from Fchart
    otm4_0 = Model4.objects.filter(OTid=otid).first()
    dic = {'otm4_0':otm4_0}
    return render(request,'OTobjects/changeStatus.html',dic)

def Comment(request,otid):
    #-Insert into Comments
    if request.POST:
        Model1.objects.filter(OTid=otid).update(status=request.POST['status'])
        Model5.objects.create(OTid_id=otid,uid_id=request.session['user_id'],status=request.POST['status'],comment=request.POST['commentarea'])
    #-Select from Comments
    otm5 = Model5.objects.filter(OTid=otid)
    counts = otm5.count()
    dic = {'otm5':otm5,'counts':counts}
    return render(request,'OTobjects/listComment.html',dic)
    #return render(request,'OTobjects/confirm.html',dic)

def LoginForm(request,confirm=False):
    if confirm:
        return render(request,'OTobjects/confirm_login.html')
    else:
        return render(request,'OTobjects/login.html')

def Login(request,confirm=False):
    '''user login ang save the user id to the session
    '''
    username = request.POST['uname']
    password = request.POST['passwd']
    if username and password:
        user = Model6.objects.filter(uname=username)
        if user:
            user = user[0]
            if password == user.passwd:
                #if user.status:
                #    return render(request,'OTobjects/login.html',{'message':"The current user has been logined, prohibit login again."})
                #else:
                    #- change the status of user loggin in database
                    user.status = True
                    user.save()
                    #- save the current user to the session
                    request.session['user_id'] = user.uid
                    if confirm:
                        return HttpResponseRedirect('/ot/image/otid=%s/index=confirm/'%OTid)
                    else:
                        return HttpResponseRedirect('/ot/index')
            else:
                return render(request,'OTobjects/login.html',{'message':"Your username and password didn't match."})
        else:
            return render(request,'OTobjects/login.html',{'message':"The user you input dose not exist and you need to signup!"})
    else:
        return render(request,'OTobjects/login.html',{'message':"Please input your user name and password!"})

def Logout(request):
    uid = request.session['user_id']
    #change the status of user
    user = Model6.objects.get(uid=uid)
    user.status = False
    user.save()
    #delete the user from the session
    del request.session['user_id']
    return HttpResponseRedirect('/ot/index')

def SignupForm(request):
    return render(request,'OTobjects/signup_form.html')

def Signup(request):
    uname = request.POST['uname']
    passwd = request.POST['passwd']
    passwdConf = request.POST['passwdConf']
    fname = request.POST['fname']
    lname = request.POST['lname']
    email = request.POST['email']
    memberIsExist = Model6.objects.filter(uname=uname)
    if memberIsExist:
        return render(request,'OTobjects/signup_form.html',{'message':"The user name you input has been used.Please use another."})
    else:
        if uname and passwd and passwdConf and fname and lname and email:
            if passwd == passwdConf:
                Model6.objects.create(uname=uname,passwd=passwd,first_name=fname,last_name=lname,email_add=email)
                return HttpResponseRedirect('/ot/login-form')
            else:
                return render(request,'OTobjects/signup_form.html',{'message':"The tow passwords you inputed do not match."})
        else:
            return render(request,'OTobjects/signup_form.html',{'message':"Please fill in all the signup information(*)."})

OTAutoSearch/OTobjects/templates/OTobjects/base.html
<html>
	<head>
		<meta charset="utf-8">
		<title> {%block title%} {%endblock%} </title>
		<style type="text/css">{%block css%}{%endblock%}</style>
		{%block js%}{%endblock%}
	</head>

	<body>
		<div id="header_out">
			{%block header%}{%endblock%}
		</div>
		<div id="content_out">
			{%block content%}{%endblock%}
		</div>
		<div id="footer_out">
			{%block footer%}{%endblock%}
		</div>
	</body>
</html>

OTAutoSearch/OTobjects/templates/OTobjects/changeStatus.html
{%extends "OTobjects/base.html"%}

{%block content%}
<form id="fstatus" action="../index=status/" method="post">
   {% csrf_token %}
   <fieldset>
     <legend><b>Confirm : </b>now status <span id="nowstatus" style="color:red;">{{otm4_0.OTid.status}}</span></legend>
     <div style="position:relative;left:80px;">
       <input type="radio" name="status" value="-1">-1
       <input type="radio" name="status" value="0" checked="checked">0
       <input type="radio" name="status" value="1">1
       <input type="radio" name="status" value="2">2
       <input type="submit" value="submit" style="position:relative;left:150px;"><br/>
       <span style="font-style:italic;"><b>*note*:</b>-1 False transient; 0 To be confirmed; 1 True transient; 2 Continue to be confirmed</span>
     </div>
   </fieldset>
</form>
{%endblock%}

OTAutoSearch/OTobjects/templates/OTobjects/confirm.html
{%extends "OTobjects/base.html"%}
{%load staticfiles%}

{%block js%}
  <script>
    function clear(id){
        document.getElementById(id).style.background="yellow";
        document.getElementById(id).value="";
    }    
  </script>
  <script type="text/javascript" src="http://libs.baidu.com/jquery/1.10.2/jquery.min.js"></script>
  <script type="text/javascript">
    $(document).ready(function(){
       $("#fcomment").submit(function(e){
           var num = parseInt($("#counts").text());
           $("#counts").text((num+1).toString());
       });
    });
  </script>
{%endblock%}

{%block content%}
<link rel="stylesheet" type="text/css" href="{% static 'OTobjects/css/confirm.css' %}" />
<div class="firstFchartTitle"><b>Fchart : </b>{{otm4_0.Catid.Catna}}<b> JD : </b>{{otm4_0.Catid.JD}}</div>
<div id='firstFchart' class="firstFchart">
    <img src="{%static 'OTobjects'%}/Fchart/{{otm4_0.Fname}}" alt="{{otm4_0.Fpath}}/{{otm4_0.Fname}}" style="align:center;"/>
</div>
<div class="commentTitle"><b>Comment</b></div>
<div id="comment" class="comment">
  <form id="fcomment" action="../index=comment/" target="listcomment" method="post">
    {% csrf_token %}
    <fieldset style="width:800px;">
    <div style="position:relative;left:10px;">
      <legend>now status <span id="nowstatus" style="color:red;">{{otm4_0.OTid.status}}</span></br></legend>
      <input type="radio" name="status" value="-1">-1
      <input type="radio" name="status" value="0" checked="checked">0
      <input type="radio" name="status" value="1">1
      <input type="radio" name="status" value="2">2</br>
      <span style="font-style:italic;"><b>*note*:</b>-1 False transient; 0 To be confirmed; 1 True transient; 2 Continue to be confirmed</span>
    </div>
    </fieldset>
    <textarea id="commentarea" name="commentarea" rows="5" cols="99" onfocus="clear(this.id)"></textarea><br/>
    <input type="submit" value="submit" style="position:relative;left:740px;">
  </form>
</div>
<div id="listcomment" class="listcomment">
  <span>Now,there are <span id="counts">{{counts}}</span> comments</span>
  <hr>
  <iframe src="../index=comment/" name="listcomment" style="width:100%;" frameborder="0" ></iframe>
</div>
{%endblock%}

OTAutoSearch/OTobjects/templates/OTobjects/confirm_login.html
{%extends "OTobjects/base.html"%}
{%load staticfiles%}

{%comment%}
   {%block js%}
       <script src="http://libs.baidu.com/jquery/1.10.2/jquery.min.js"></script>
       <script>
	 $(document).ready(function(){ 
             $("form").attr("action","http://www.w3cschool.cc/jquery");
	 });
       </script>
   {%endblock%}
{%endcomment%}

{%block css%}
{%endblock%}

{%block content%}
<link rel="stylesheet" type="text/css" href="{% static 'OTobjects/css/login.css'%}"/>
<div id="login" class="login">
  <div id="login_h" class="login_h" >
    <div class="login_title">
      <b>User login</b>
    </div>
  </div>
  <div id="login_c" class="login_c">
    <div id="form" style="position:relative; top:30px;">
      <form action="{%url 'OTobjects:confirm_login'%}" method="post">
	{%csrf_token%}
	Username:&nbsp;<input type="text" name="uname" autofocus><br>
	Password:&nbsp;<input type="password" name="passwd"><br>
    </div>
    <div id="message" style="line-height:50px;">
      <span style="color:red;">{{message}}</span>
    </div>	
  </div>
  <div id="login_f" class="login_f">
    <div id="signup" style="height:100%; width:50%; float:left;">
      <div id="signup" style="position:relative; left:20px; top:15px;">
	<a href="{%url 'OTobjects:signup_form'%}">signup</a>
      </div>
    </div>
    <div id="submit" style="height:100%; width:50%; float:left;">
      <div id="submit" style="position:relative; left:100px; top:10px;">
	<input type="submit" value="Login">
        </form>
      </div>
    </div>
  </div>
</div>
{%endblock%}

OTAutoSearch/OTobjects/templates/OTobjects/index.html
{%extends "OTobjects/base.html"%}
{%load i18n%}
{%load staticfiles%}

{%block css%}
    body{background:url("{%static 'OTobjects'%}/image/bg_content.png");}
{%endblock%}

{%block title%}{%trans 'OTsearch'%}{%endblock%}

{%block header%}
<link rel="stylesheet" type="text/css" href="{% static 'OTobjects/css/index.css'%}"/>
<div id="header">
  <div id="site-name" class="index_h" style="width:70%;float:left;text-align:right;">
    {{"Transient management system"|title}}
  </div>
  <div id="login" class="index_h" style="width:30%;float:right;text-align:center;">
    {%if userstatus%}
        <span class="welcome">Welcome<span style="color:#99CC33;">&nbsp;<b>{{username}}</span>.<a class="logout" href="{%url 'OTobjects:logout'%}">Logout</a></span>
    {%else%}
	<a class="login" href="{%url 'OTobjects:login_form'%}">Login</a>
    {%endif%}
  </div>
</div>
{%endblock%}

{%block content%}
<table class="index_t" style="clear:both">
  <tr class="thead">
    <th>OTid</th><th>X</th><th>Y</th><th>Ra</th><th>Dec</th><th>Magcalib</th><th>Magorig</th><th>MagorigErr</th><th>Magres</th><th>MagresErr</th><th>Counts</th>
    <th>
      <ul id="status">
        <li><a href="{%url 'OTobjects:index'%}">Status</a>
        <ul>
          <li><a href="/ot/status=-1">-1</a>
          <li><a href="/ot/status=0">0</a>
          <li><a href="/ot/status=1">1</a>
          <li><a href="/ot/status=2">2</a>
          <li><a href="{%url 'OTobjects:index'%}">all</a>
        </ul>
      </ul>
    </th>
  </tr>
{%for o in otm1%}
   <tr class="tdata">
     <td>{{o.OTid}}</td><td>{{o.x|floatformat:4}}</td><td>{{o.y}}</td><td>{{o.Ra}}</td><td>{{o.Dec}}</td><td>{{o.magcalib}}</td><td>{{o.magorig|floatformat:2}}</td><td>{{o.magorigErr|floatformat:3}}</td><td>{{o.magres|floatformat:2}}</td><td>{{o.magErr|floatformat:4}}</td>
     <td><a class="counts" href="/ot/image/otid={{o.OTid}}" target="_blank">{{o.counts}}</a></td>
     <td>{%if o.status == -1 %}
             <span title="False transient">-1</span>
         {%elif o.status == 0 %}
             <span title="To be confirmed">0</span>
         {%elif o.status == 1 %}
             <span title="True transient">1</span>
         {%else%}
             <span title="Continue to be confirmed">2</span>
         {%endif%}
     </td>
   </tr>
{%endfor%}
</table>
{%endblock%}

{%block footer%}
{%if otm1%}
  <span style="position:relative;top:5px;"><i><b>*status*:</b>-1 False transient; 0 To be confirmed; 1 True transient; 2 Continue to be confirmed</i></span>
  <div style="text-align:center;position:relative;top:15px;">
    {#previous#}
    {%if otm1.has_previous%}
        <a class="paginator-pages" href="./page={{page|add:'-1'}}">previous</a>
    {%endif%}
    {#the center pages.If the number of pages is less than or equeal to 10,all pages will be displayed. If it's greater than 10,"..." will be displayed.Before "...",only display one page.After "...",only display ten pages.#}
    {#<=10#}
    {%if paginator.num_pages <= 10%}
         {%for i in paginator.page_range%}
              {%if i == page%}
                  <b>{{i}}</b>
              {%else%}
                  <a class="paginator-pages" href="./page={{i}}">{{i}}</a>
              {%endif%}
         {%endfor%}
    {%endif%}
    {#>10#}
    {%if paginator.num_pages > 10%}
         {%if page >= 4 %}
             <a class="paginator-pages" href="./page=1">1</a>
             ...
             {%for i in paginator.page_range%}
                  {%if i >= page_start and i <= page_end%}
                       {%if i == page%}
                           <b>{{i}}</b>
                       {%else%}
                           <a class="paginator-pages" href="./page={{i}}">{{i}}</a>
                       {%endif%}
                  {%endif%}
             {%endfor%}
         {%else %}
             {%for i in paginator.page_range%}
                  {%if i == page %}
                       <b>{{i}}</b>
                  {%else%}
                       {%if i <= 8%}
                           <a class="paginator-pages" href="./page={{i}}">{{i}}</a>
                       {%endif%}
                  {%endif%}
             {%endfor%}
         {%endif%}
    {%endif%}
    {#next#}
    {%if otm1.has_next%}
         <a class="paginator-pages" href="./page={{page|add:'1'}}">next</a>
    {%endif%}
  </div>
{%else%}
  <div style="color:red;position:relative;top:100px;text-align:center;">
     <p><b>Sorry,there are no datasets for you.</b></p>
  </div>
{%endif%}
{%endblock%}

OTAutoSearch/OTobjects/templates/OTobjects/listComment.html
{%extends "OTobjects/base.html"%}

{%block content%}
{%for o in otm5%}
   <b>{{o.uid.uname}}</b>: &nbsp;{{o.comment}}<br>
   <span style="font-size:70%;position:absolute;left:60%;">status: <span style="color:red;">{{o.status}}</span></span><span style="font-size:70%;position:absolute;right:10%;">{{o.datetime|date:"Y-m-d H:i:s"}}</span>
{%endfor%}
{%endblock%}

OTAutoSearch/OTobjects/templates/OTobjects/login.html
{%extends "OTobjects/base.html"%}
{%load staticfiles%}

{%block css%}
{%endblock%}

{%block content%}
<link rel="stylesheet" type="text/css" href="{% static 'OTobjects/css/login.css'%}"/>
<div id="login" class="login">
  <div id="login_h" class="login_h" >
    <div class="login_title">
      <b>User login</b>
    </div>
  </div>
  <div id="login_c" class="login_c">
    <div id="form" style="position:relative; top:30px;">
      <form action="{%url 'OTobjects:login'%}" method="post">
	{%csrf_token%}
	Username:&nbsp;<input type="text" name="uname" autofocus><br>
	Password:&nbsp;<input type="password" name="passwd"><br>
    </div>
    <div id="message" style="line-height:50px;">
      <span style="color:red;">{{message}}</span>
    </div>	
  </div>
  <div id="login_f" class="login_f">
    <div id="signup" style="height:100%; width:50%; float:left;">
      <div id="signup" style="position:relative; left:20px; top:15px;">
	<a href="{%url 'OTobjects:signup_form'%}">signup</a>
      </div>
    </div>
    <div id="submit" style="height:100%; width:50%; float:left;">
      <div id="submit" style="position:relative; left:100px; top:10px;">
	<input type="submit" value="Login">
        </form>
      </div>
    </div>
  </div>
</div>
{%endblock%}

OTAutoSearch/OTobjects/templates/OTobjects/showFchart.html
{%extends "OTobjects/base.html"%}
{%load staticfiles%}

{%block content%}
<link rel="stylesheet" type="text/css" href="{% static 'OTobjects/css/showFchart.css' %}" />
<div id='tb' class='tb' >
  <table  border=1>
    <tr align=center>
      <th>Catfile</th><th>JD</th><th>Fchart</th>
    </tr>
    {%for o4 in otm4%}
      <tr>
	<td>{{o4.Catid.Catna}}</td>
	<td>{{o4.Catid.JD}}</td>
	<td><img src="{%static 'OTobjects'%}/Fchart/{{o4.Fname}}" alt="{{o4.Fpath}}/{{o4.Fname}}"/></td>
      </tr>
    {%endfor%}
  </table>
</div>
{%endblock%}

OTAutoSearch/OTobjects/templates/OTobjects/signup_form.html
{%extends "OTobjects/base.html"%}

{%load staticfiles%}

{%block css%}
{%endblock%}

{%block content%}
<link rel="stylesheet" type="text/css" href="{% static 'OTobjects/css/signup.css'%}"/>
<div id="signup" class="signup">
  <div id="signup_h" class="signup_h">
    <b>User Signup Form</b>
  </div>
  <div id="signup_c" class="signup_c">
    <form action="{%url 'OTobjects:signup'%}" method="POST">
      {%csrf_token%}
      <div id="left" class="left" style="width:40%; height:95%;">
	username&nbsp;:<br>
	password&nbsp;:<br>
	password confirmation&nbsp;:<br>
	First name&nbsp;:<br>
	Last name&nbsp;:<br>
	Email address&nbsp;:<br>
      </div>
      <div id="right" class="right" style="width:60%; height:95%;">
	&nbsp;<input type="text" name="uname" autofocus><span> *</span><br>
	&nbsp;<input type="password" name="passwd"><span> *</span><br>
	&nbsp;<input type="password" name="passwdConf"><span> *</span><br>
	&nbsp;<input type="text" name="fname"><span> *</span><br>
	&nbsp;<input type="text" name="lname"><span> *</span><br>
	&nbsp;<input type="email" name="email"><span> *</span><br>
      </div>
      <div id="message" class="signup_message">
	<span style="color:red;">{{message}}</span>
      </div>
      <div id="signup_f" class="signup_f">
	<input type="submit" value="submit" style="position:relative; left:450px; top:10px;">
        </form>
   </div>
 </div>
{%endblock%}